// <auto-generated />
using System;
using Amnesia.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Amnesia.Domain.Migrations
{
    [DbContext(typeof(BlockchainContext))]
    [Migration("20190605150330_Another migration reset")]
    partial class Anothermigrationreset
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview5.19227.1");

            modelBuilder.Entity("Amnesia.Domain.Entity.Block", b =>
                {
                    b.Property<byte[]>("Hash");

                    b.Property<byte[]>("ContentHash");

                    b.Property<int>("Nonce");

                    b.Property<byte[]>("PreviousBlockHash");

                    b.HasKey("Hash");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("PreviousBlockHash");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("Amnesia.Domain.Entity.Content", b =>
                {
                    b.Property<byte[]>("Hash");

                    b.Property<string>("Definitions");

                    b.Property<string>("Mutations");

                    b.HasKey("Hash");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Amnesia.Domain.Entity.Data", b =>
                {
                    b.Property<byte[]>("Hash");

                    b.Property<byte[]>("Blob");

                    b.Property<string>("Key");

                    b.Property<byte[]>("PreviousDefinitionHash");

                    b.Property<byte[]>("Signature");

                    b.HasKey("Hash");

                    b.HasIndex("PreviousDefinitionHash")
                        .IsUnique();

                    b.ToTable("Data");
                });

            modelBuilder.Entity("Amnesia.Domain.Entity.Definition", b =>
                {
                    b.Property<byte[]>("Hash");

                    b.Property<byte[]>("DataHash");

                    b.Property<bool>("IsMutable");

                    b.Property<bool>("IsMutation");

                    b.Property<string>("Key");

                    b.Property<byte[]>("PreviousDefinitionHash");

                    b.Property<byte[]>("Signature");

                    b.HasKey("Hash");

                    b.HasIndex("PreviousDefinitionHash")
                        .IsUnique();

                    b.ToTable("Definitions");
                });

            modelBuilder.Entity("Amnesia.Domain.Entity.State", b =>
                {
                    b.Property<string>("PeerId");

                    b.Property<byte[]>("CurrentBlockHash");

                    b.HasKey("PeerId");

                    b.HasIndex("CurrentBlockHash");

                    b.ToTable("State");
                });

            modelBuilder.Entity("Amnesia.Domain.Entity.Block", b =>
                {
                    b.HasOne("Amnesia.Domain.Entity.Content", "Content")
                        .WithOne("Block")
                        .HasForeignKey("Amnesia.Domain.Entity.Block", "ContentHash");

                    b.HasOne("Amnesia.Domain.Entity.Block", "PreviousBlock")
                        .WithMany()
                        .HasForeignKey("PreviousBlockHash");
                });

            modelBuilder.Entity("Amnesia.Domain.Entity.Data", b =>
                {
                    b.HasOne("Amnesia.Domain.Entity.Definition", null)
                        .WithOne()
                        .HasForeignKey("Amnesia.Domain.Entity.Data", "PreviousDefinitionHash");
                });

            modelBuilder.Entity("Amnesia.Domain.Entity.Definition", b =>
                {
                    b.HasOne("Amnesia.Domain.Entity.Definition", "PreviousDefinition")
                        .WithOne()
                        .HasForeignKey("Amnesia.Domain.Entity.Definition", "PreviousDefinitionHash");
                });

            modelBuilder.Entity("Amnesia.Domain.Entity.State", b =>
                {
                    b.HasOne("Amnesia.Domain.Entity.Block", "CurrentBlock")
                        .WithMany()
                        .HasForeignKey("CurrentBlockHash");
                });
#pragma warning restore 612, 618
        }
    }
}
