// <auto-generated />
using System;
using Amnesia.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Amnesia.Domain.Migrations
{
    [DbContext(typeof(BlockchainContext))]
    [Migration("20190520120136_New initial migration bc sqlite sucks")]
    partial class Newinitialmigrationbcsqlitesucks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Amnesia.Domain.Entity.Block", b =>
                {
                    b.Property<byte[]>("Hash")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("ContentHash");

                    b.Property<int>("Nonce");

                    b.Property<byte[]>("PreviousBlockHash");

                    b.HasKey("Hash");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("PreviousBlockHash");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("Amnesia.Domain.Entity.Content", b =>
                {
                    b.Property<byte[]>("Hash")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Definitions");

                    b.Property<string>("Mutations");

                    b.HasKey("Hash");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Amnesia.Domain.Entity.Data", b =>
                {
                    b.Property<byte[]>("Hash")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Blob");

                    b.Property<byte[]>("Key");

                    b.Property<byte[]>("PreviousDefinitionHash");

                    b.Property<byte[]>("Signature");

                    b.HasKey("Hash");

                    b.HasIndex("PreviousDefinitionHash")
                        .IsUnique();

                    b.ToTable("Data");
                });

            modelBuilder.Entity("Amnesia.Domain.Entity.Definition", b =>
                {
                    b.Property<byte[]>("Hash")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("DataHash");

                    b.Property<bool>("IsMutation");

                    b.Property<byte[]>("Key");

                    b.Property<string>("Meta");

                    b.Property<byte[]>("PreviousDefinitionHash");

                    b.Property<byte[]>("Signature");

                    b.HasKey("Hash");

                    b.HasIndex("DataHash")
                        .IsUnique();

                    b.HasIndex("PreviousDefinitionHash")
                        .IsUnique();

                    b.ToTable("Definitions");
                });

            modelBuilder.Entity("Amnesia.Domain.Entity.State", b =>
                {
                    b.Property<string>("PeerId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("CurrentBlockHash");

                    b.HasKey("PeerId");

                    b.HasIndex("CurrentBlockHash");

                    b.ToTable("State");
                });

            modelBuilder.Entity("Amnesia.Domain.Entity.Block", b =>
                {
                    b.HasOne("Amnesia.Domain.Entity.Content", "Content")
                        .WithOne("Block")
                        .HasForeignKey("Amnesia.Domain.Entity.Block", "ContentHash");

                    b.HasOne("Amnesia.Domain.Entity.Block", "PreviousBlock")
                        .WithMany()
                        .HasForeignKey("PreviousBlockHash");
                });

            modelBuilder.Entity("Amnesia.Domain.Entity.Data", b =>
                {
                    b.HasOne("Amnesia.Domain.Entity.Definition")
                        .WithOne()
                        .HasForeignKey("Amnesia.Domain.Entity.Data", "PreviousDefinitionHash");
                });

            modelBuilder.Entity("Amnesia.Domain.Entity.Definition", b =>
                {
                    b.HasOne("Amnesia.Domain.Entity.Data", "Data")
                        .WithOne()
                        .HasForeignKey("Amnesia.Domain.Entity.Definition", "DataHash");

                    b.HasOne("Amnesia.Domain.Entity.Definition", "PreviousDefinition")
                        .WithOne()
                        .HasForeignKey("Amnesia.Domain.Entity.Definition", "PreviousDefinitionHash");
                });

            modelBuilder.Entity("Amnesia.Domain.Entity.State", b =>
                {
                    b.HasOne("Amnesia.Domain.Entity.Block", "CurrentBlock")
                        .WithMany()
                        .HasForeignKey("CurrentBlockHash");
                });
#pragma warning restore 612, 618
        }
    }
}
